consul:
    image: progrium/consul
    container_name: consul
    ports:
        - "8400:8400"
        - "8500:8500"
        - "127.17.42.1:8600:53/udp"
    command:
        -server 
        -bootstrap 
        -ui-dir /ui
        -advertise 10.50.1.114
redis:
    image: redis
    container_name: redis
    ports:
        - "6379:6379"
hello:
    build: ./api_redis
    container_name: hello
    ports:
        - "5004:5004"