version: "2"
services:
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
    hello:
        build: ./api_redis
        container_name: hello
        ports:
            - "5004:5004"