redis:
    image: redis
    container_name: redis
    ports:
        - "6379:6379"
    volumes_from:
        - "redis_data"
    command: redis-server --appendonly yes
hello_world:
    build: ./api_redis
    container_name: hello_world
    ports:
        - "5004:5004"