version: "2"
services:
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        volumes: 
            - redis_data:/data
        command: redis-server --appendonly yes
    hello:
        build: ./api_redis
        image: demo/hello
        container_name: hello
        ports:
            - "5004:5004"
volumes:
    redis_data:
        external:
            name: redis_data