version: "2"
services:
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
    hello:
        build: ../api_logging
        container_name: hello
        ports:
            - "5020:5020"
        logging:
            driver: gelf
            options:
                gelf-address: "udp://172.17.0.1:5037"